name: Trigger_Email_Workflow

on:
  workflow_dispatch

jobs:
  job1:
    name: Trigger_Email
    runs-on: windows-latest
    steps:
    - name: Run PowerShell script
      uses: actions/powershell@v3
      with:
        args: ./Modules/Module15.ps1

