name: Trigger_Email_Workflow

on:
  workflow_dispatch

jobs:
  job1:
    name: Trigger_Email
    runs-on: windows-latest
    steps:
    - name: Azure PowerShell Action1
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          ./Modules/Module15.ps1
        azPSVersion: "latest"
