name: Trigger_Email_Workflow

on:
  workflow_dispatch

jobs:
  job1:
    name: Trigger_Email
    runs-on: windows-latest
    steps:
    - name: Run PowerShell script
      shell: pwsh
      run: |
        ./Modules/Module15.ps1

